python train_test_QM9.py --property 0
python train_test_QM9.py --property 1
python train_test_QM9.py --property 2
python train_test_QM9.py --property 3
python train_test_QM9.py --property 4
python train_test_QM9.py --property 5
python train_test_QM9.py --property 6
python train_test_QM9.py --property 7
python train_test_QM9.py --property 8
python train_test_QM9.py --property 9
python train_test_QM9.py --property 10